client imaging work

diff --git a/clonedeploy_web/web/data/clientscripts/core/cd_global_functions b/clonedeploy_web/web/data/clientscripts/core/cd_global_functions
--- a/clonedeploy_web/web/data/clientscripts/core/cd_global_functions
+++ b/clonedeploy_web/web/data/clientscripts/core/cd_global_functions
@@ -248,5 +248,90 @@ function mount_smb()
 	sleep 2
 }
 
+function process_scripts()
+{
+  local scripts="$1"
+  for script_id in $scripts; do
+    $curlAuth --data "scriptId=$script_id" "${web}GetCustomScript" $curlEnd > /tmp/custom_script
+	log " ** Running Custom Script With Id $script_id ** " "display"
+	#source script in sub shell so the values of the core script do not get overwritten
+	( . /tmp/custom_script )
+  done
+}
 
+function process_sysprep_tags()
+{
+  local partition="$1"
+  log " ** Processing Sysprep Tags On $partiton ** " "display"
+  mkdir /mnt/ntfs &> /dev/null	
+  ntfs-3g -o force,rw,remove_hiberfile $partition /mnt/ntfs &>/dev/null
+  if [ "$?" != "0" ]; then
+    log "Could Not Mount NTFS To Change Answer File"
+	return 1
+  fi
+  
+  if [ -f "/mnt/ntfs/Windows/Panther/unattend.xml" ]; then
+    log " ...... Found Answer File, Updating Answer File" "display"
+	for tag_id in $sysprep_tags; do
+      sysprep_tag_json=$($curlAuth --data "tagId=$tag_id" "${web}GetSysprepTag" $curlEnd)
+	  perl -0777 -i -pe "s/($(parse_json "$sysprep_tag_json" .OpeningTag)).*($(parse_json "$sysprep_tag_json" .ClosingTag))/\$1$(parse_json "$sysprep_tag_json" .Contents)\$2/s" /mnt/ntfs/Windows/Panther/unattend.xml
+    done
+  else
+    log " ...... Could Not Find Answer File"
+  fi
+}
+
+function process_file_copy()
+{
+  local current_object="$1"
+  local object_type="$2"
+  local array_index=-1
+  while [  "$(( $array_index + 1 ))" -lt "$(parse_json "$file_copy_schema" .Count)" ]; do
+    array_index=$(( $array_index + 1))
+    clear_and_move_down
+    current_file="$(parse_json "$file_copy_schema" .FilesAndFolders[$array_index])"
+    log "$current_file"
+	if [ "$object_type" = "partition" ]; then
+	  if [ "$(parse_json "$current_object" .Number)" = "$(parse_json "$current_file" .DestinationPartition)" ]; then
+	    log "Copying /storage/resources/$(parse_json "$current_file" .SourcePath)"
+		if [ "$(parse_json "$current_object" .FileSystem)" = "ntfs" ]; then
+          mkdir /mnt/ntfs &> /dev/null
+		  ntfs-3g -o force,rw,remove_hiberfile ${hard_drive}${partition_prefix}$(parse_json "$current_object" .Number) /mnt/ntfs &>/dev/null
+          if [ "$?" != "0" ]; then
+            log "Could Not Mount NTFS"
+	        return 1
+          fi
+		  
+		  if [ -d "/storage/resources/$(parse_json "$current_file" .SourcePath)" ]; then
+		    cp -R "/storage/resources/$(parse_json "$current_file" .SourcePath)" "/mnt/ntfs/$(parse_json "$current_file" .DestinationFolder)"
+		  else
+            cp "/storage/resources/$(parse_json "$current_file" .SourcePath)" "/mnt/ntfs/$(parse_json "$current_file" .DestinationFolder)"
+		  fi
+		else # only ext or xfs
+		  mkdir /mnt/fs &> /dev/null
+		  mount ${hard_drive}${partition_prefix}$(parse_json "$current_object" .Number) /mnt/fs
+		   if [ "$?" != "0" ]; then
+             log "Could Not Mount Filesystem"
+	         return 1
+           fi
+		fi
+	  fi
+	else # object_type = lvm
+	
+	fi
+  done
+}
+
+function update_registry_key()
+{
+  local root="$1"
+  local key="$2"
+  local value="$3"
+  reged -e "$root" &>>$CLIENT_LOG  <<EOFN 
+ed $key
+$value
+q
+y
+EOFN
+}
 
