more client work

diff --git a/clonedeploy_web/web/data/clientscripts/core/pull b/clonedeploy_web/web/data/clientscripts/core/pull
--- a/clonedeploy_web/web/data/clientscripts/core/pull
+++ b/clonedeploy_web/web/data/clientscripts/core/pull
@@ -6,9 +6,62 @@ isond="$1"
 taskArgs="$2"
 logBootArgs
 
+function GetLogicalVolumes()
+{
+	if [ -n "$custom_logical_volumes" ]; then
+		lvmLVS=`echo "$custom_logical_volumes" | grep "$lvmVG"`
+		#escaped on server
+		log " ...... Logical Volumes Overridden By User, User Specified $lvmLVS" "display"		
+	else
+		tmpLvmLVS=$(lvs | grep "$lvmVG" | awk '/^ / {print $1}')	
+		#Escape - in vg or lv
+		esVG=$(echo $lvmVG | sed 's/-/--/g')
+		for lv in $tmpLvmLVS; do
+			esLV=$(echo $lv | sed 's/-/--/g')
+			lvmLVS="$lvmLVS $esVG-$esLV"
+		done
+		
+	fi
+									
+	lvmLVSCount=0
+	for lv in $lvmLVS; do
+		lvmLVSCount=$(( $lvmLVSCount + 1 ))
+	done
+}
+
+function GetPartitions()
+{
+	partitions=""
+	log " ** Determining Partition Count On $hd ** " "display"
+	if [ -n "$custom_partitions" ]; then
+		for tmpPart in $custom_partitions; do
+			echo "$tmpPart" | grep $hd
+			if [ "$?" = "0" ]; then
+				partitions="$partitions $tmpPart"
+			fi
+		done
+		log " ...... Partitions Overridden By User, User Specified $partitions" "display"		
+	else
+		partitions=$(lsblk -ipno KNAME | grep "$hd" | grep -vw "$hd" 2>> /tmp/clientlog.log)	
+	fi
+		
+	partCount=0	
+	for part in $partitions; do
+		partCount=$(( $partCount + 1 ))
+	done
+	
+	sleep 2
+	
+	if [ "$partCount" = "0" ]; then
+		error "Unable To Determine Partition Count Or There Are No Partitions On This Drive"
+	fi	
+	log " ...... Found $partCount Partition(s)" "display"
+	echo
+}
+
 function shrinkFS()
 {
-	if [ "$noResize" != "true" ]; then
+
 		if [ "$fsType" = "ext2" ] || [ "$fsType" = "ext3" ] || [ "$fsType" = "ext4" ]; then
 			newextsize="";
 			log " ...... Shrinking EXT Volume On $1 (This May Take A Few Minutes) " "display"
@@ -23,13 +76,16 @@ function shrinkFS()
 			if [ ! "$?" = "0" ]; then
 				log "Warning, EXT File System Did Not Shrink Properly. " "display"
 			else
-				shrunkParts="$shrunkParts $1 "
+				shrunkVolumes="$shrunkVolumes $1 "
 				log " ...... Success" "display"
 			fi
 
 			log " ...... extfssize: $extfssize fsblksize: $fsblksize minpartsize: $minpartsize"
 
 		elif [ "$fsType" = "ntfs" ]; then
+			if [ "$image_type" = "file" ]; then #If we are doing a file based clone, the volume does not need to be shrunk
+				return 0
+			fi
 			log " ...... Shrinking NTFS Volume On $1 (This May Take A Few Minutes) " "display"
 			fsCheck=`ntfsresize -i $1 | grep "chkdsk /f"`
 			if [ "$?" = "0" ]; then
@@ -46,19 +102,19 @@ CONFIRM
 			if [ ! "$?" = "0" ]; then
 				log "Warning, NTFS File System Did Not Shrink Properly. " "display"
 			else
-				shrunkParts="$shrunkParts $1 "
+				shrunkVolumes="$shrunkVolumes $1 "
 				log " ...... Success" "display"
 			fi
 			log " ...... ntfssize: $ntfssize"
 			
 			ntfsfix -b -d $1 &>>/tmp/clientlog.log
 		fi
-	fi
+	
 }
 
 function calcSize()
 {
-	log " ** Resizing Volumes And Calculating Image Specs ** " "display"
+	log " ** Resizing Volumes And Calculating Image Schema ** " "display"
 	sleep 1
 	mkdir /mnt/ntfs 2>> /tmp/clientlog.log
 	
@@ -85,17 +141,7 @@ function calcSize()
 		fi
 		stringHD="{\"name\":\"$hd\",\"size\":\"$dsize\",\"table\":\"$ptType\",\"boot\":\"$hboot\",\"lbs\":\"$lbs\",\"pbs\":\"$pbs\",\"guid\":\"$hdGUID\",\"active\":\"true\",\"partitions\": [ "
 		
-		partitions=$(lsblk -ipno KNAME | grep "$hd" | grep -vw "$hd" 2>> /tmp/clientlog.log)
-		partCount=0	
-		for part in $partitions; do
-			partCount=$(( $partCount + 1 ))
-		done
-	
-		sleep 2
-	
-	if [ "$partCount" = "0" ]; then
-		error "Unable To Determine Partition Count Or There Are No Partitions On This Drive"
-	fi	
+		GetPartitions
 		
 		counter=0
 		for part in $partitions; do
@@ -136,10 +182,12 @@ function calcSize()
 			else
 				fsid=$(gdisk $hd -l | grep " $x " | awk '/^ / {print $6}')
 			fi
-								
-			if [ "$noResize" != "true" ] && [ "$pMBSize" -gt "2000" ]; then #partition smaller than 2GB probably that way for a reason, leave it alone.
+						
+			if [ "$skip_shrink_volumes" != "true" ] && [ "$upload_schema_only" != "true" ] && [ "$pMBSize" -gt "5000" ]; then #partition smaller than 5GB probably that way for a reason, leave it alone.
 				if [ "$fsType" = "ext2" ] || [ "$fsType" = "ext3" ] || [ "$fsType" = "ext4" ] || [ "$fsType" = "ntfs" ]; then
-					shrinkFS $hd$x					
+					if [[ ! "$custom_fixed_partitions" == *"$hd$x"* ]]; then
+						shrinkFS $hd$x			
+					fi
 				fi
 			fi
 
@@ -169,14 +217,11 @@ function calcSize()
 					lvmVGSize=$(vgs 2>/dev/null --units s | grep "$lvmVG" | awk '/^ /  {print $6}' | sed 's/S$//')
 					stringVG="\"name\":\"$lvmVG\",\"size\":\"$lvmVGSize\",\"type\":\"vg\",\"physicalvolume\":\"$part\",\"uuid\":\"$lvmVGUUID\",\"logicalvolumes\": [ "
 				
-					lvmLVS=$(lvs | grep "$lvmVG" | awk '/^ / {print $1}')
-					lvmLVSCount=$(lvs | grep "$lvmVG" -c)
+					GetLogicalVolumes
+					
 					lvCounter=0
 					for logical_volume in $lvmLVS; do
-						#Escape - in vg or lv
-						esVG=$(echo $lvmVG | sed 's/-/--/g')
-						esLV=$(echo $logical_volume | sed 's/-/--/g')
-						lvHD="/dev/mapper/$esVG-$esLV"
+						lvHD="/dev/mapper/$logical_volume"
 						lvCounter=$(( $lvCounter + 1 ))
 						fsType=`blkid -po udev "$lvHD" | grep FS_TYPE | awk -F'=' '{print $2}'`
 						lvUUID=`lvs -v 2>/dev/null | grep "$lvmVG" | grep "$logical_volume" | awk '/^ / {print $10}'`
@@ -198,9 +243,7 @@ function calcSize()
 						fi
 					
 						
-					
-						#Fix Me
-						if [ "$noResize" != "true" ] && [ "$pMBSize" -gt "2000" ]; then #partition smaller than 2GB probably that way for a reason, leave it alone.
+						if [ "$skip_shrink_volumes" != "true" ] && [ "$upload_schema_only" != "true" ] && [ "$skip_shrink_lvm" != "true" ] && [ "$pMBSize" -gt "5000" ]; then #partition smaller than 5GB probably that way for a reason, leave it alone.
 							if [ "$fsType" = "ext2" ] || [ "$fsType" = "ext3" ] || [ "$fsType" = "ext4" ] || [ "$fsType" = "ntfs" ]; then
 								shrinkFS $lvHD			
 							fi
@@ -289,7 +332,7 @@ function uploadImage()
 			compBinary="lz4"
 		elif [ "$compression_algorithm" = "gzip" ]; then
 			compExt="gz"
-			compBinary="/usr/bin/gzip"			
+			compBinary="gzip"			
 		else
 			error "Could Not Determine Current Compression Algorithm $compAlg"
 		fi
@@ -317,13 +360,16 @@ function uploadImage()
 		elif [ "$fsType" = "hfsplus" ]; then
 			partCloneType="hfsp"
 			#I don't know why but partclone.hfsp used with lz4 results in a corrupted image file, always use gzip with hfs
-			compBinary="/usr/bin/gzip"
+			compBinary="gzip"
 			compExt="gz"
+		
+		elif [ "$fsType" = "xfs" ]; then
+			partCloneType="xfs"
 			
 		elif [ "$fsType" = "swap" ]; then
 			log " ...... $part Is A Swap Partition.  Skipping." "display"
 			sleep 2
-			clear
+			ClearAndMoveDown
 			continue	
 		else
 			if [ "$isLVM" != "true" ]; then
@@ -335,7 +381,7 @@ function uploadImage()
 						log " ...... $part Is An LVM Physical Partition.  Skipping." "display"
 						log " ...... Logical Volumes Will Be Uploaded Last." "display"
 						sleep 5
-						clear
+						ClearAndMoveDown
 						continue
 					fi
 				fi
@@ -343,7 +389,7 @@ function uploadImage()
 				if [ "$fsid" = "5" ] || [ "$fsid" = "f" ] ; then
 						log " ...... $part Is An Extended Partition.  Skipping." "display"
 						sleep 2
-						clear
+						ClearAndMoveDown
 						continue
 				fi
 			fi
@@ -358,11 +404,8 @@ function uploadImage()
 		
 				log " ...... reporter $hostName $web & partclone.$partCloneType -B -c -s $part | $compBinary $compression_level -c > $imgPath/$unesImageOut.$partCloneType.$compExt"		
 				reporter $hostName $web & partclone.$partCloneType -B -c -s $part | $compBinary $compression_level -c > $imgPath/$unesImageOut.$partCloneType.$compExt
-			
-			
 		else
-		
-		
+				
 				log " ...... reporter $hostName $web & partclone.$partCloneType -B -c -s $hd$partNumber | $compBinary $compression_level -c > $imgPath/part$partNumber.$partCloneType.$compExt"		
 				reporter $hostName $web & partclone.$partCloneType -B -c -s $hd$partNumber | $compBinary $compression_level -c > $imgPath/part$partNumber.$partCloneType.$compExt
 			
@@ -370,12 +413,12 @@ function uploadImage()
 		fi
 		rm /tmp/clone.progress
 		cat /var/log/partclone.log >> /tmp/clientlog.log
-		clear
+		ClearAndMoveDown
 	done
 }
 
 
-
+#Main
 if [ "$isond" = "true" ]; then
 	log " ** Using On Demand Mode ** "
 	for arg in "$taskArgs"; do case "$arg" in *=*) eval "$arg"; log "$arg"; esac; done
@@ -401,11 +444,13 @@ if [ "$isond" != "true" ]; then
 fi
 
 log " ** Removing All Files For Existing Image: $image_name ** "
-	`$curlAuth --data "imageId=$image_id" "${web}DeleteImage" $curlEndRedirect`
+	`$curlAuth --data "profileId=$profile_id" "${web}DeleteImage" $curlEndRedirect`
 
 
 calcSize
-
+if [ "$upload_schema_only" = "true" ]; then
+	checkout
+fi
 
 hdPass=0
 for hd in $hard_drives; do
@@ -413,7 +458,7 @@ for hd in $hard_drives; do
 
 	imgPath=/storage/images/$image_name/hd$hdPass
 			
-	log " ** Checking For Partition Table Types Before Upload ** "
+	log " ** Checking For Partition Table Types Before Upload On $hd ** "
 	upGPT=`gdisk -l $hd <<< "q" 2>> /tmp/clientlog.log | grep 'GPT:' | awk '{$1=""; print $0}' | sed 's/^ //'`
 	if [ "$upGPT" = "present" ]; then
 		usingGPT=true
@@ -427,27 +472,13 @@ for hd in $hard_drives; do
 	log " ...... upGPT: $upGPT upMBR: $upMBR" 
 	
 	
-	log " ** Determining Partition Count ** " "display" 
-	partitions=$(lsblk -ipno KNAME | grep "$hd" | grep -vw "$hd" 2>> /tmp/clientlog.log)
-	
-	partCount=0	
-	for part in $partitions; do
-		partCount=$(( $partCount + 1 ))
-	done
-	
-	sleep 2
-	
-	if [ "$partCount" = "0" ]; then
-		error "Unable To Determine Partition Count Or There Are No Partitions On This Drive"
-	fi	
-	log " ...... Found $partCount Partition(s)" "display"
-	echo
+	GetPartitions
 		
 		
 	mkdir $imgPath 2>> /tmp/clientlog.log
 	
 	
-	log " ** Saving MBR / GPT ** " "display"	
+	log " ** Saving MBR / GPT On $hd ** " "display"	
 
 	if [ "$usingGPT" = "true" ]; then
 		checkPartStart=$(gdisk $hd -l | awk '/^ / {print $2+0}' | grep -vw "0" | sort -n | head -n1)
@@ -509,55 +540,48 @@ MOUNT
 		
 		
 	uploadImage
-	clear
-	
-	for part in $partitions; do
-		x=`echo $part | awk -F $hd ' {print $2}'`
-		fsType=`blkid -po udev $hd$x | grep FS_TYPE | awk -F'=' '{print $2}'`
-		expandFS $hd$x
-	done
+	ClearAndMoveDown
 	
 	if [ "$lvmExists" = "true" ]; then
-		lvmVGS=$(pvs --noheadings | grep $hd | awk '/^ / {print $2}')
-	if [ "$?" != "0" ]; then
-		return 0
-	fi
+			lvmVGS=$(pvs --noheadings | grep $hd | awk '/^ / {print $2}')
+		if [ "$?" != "0" ]; then
+			return 0
+		fi
 	
-	for VG in $lvmVGS; do
-		partitions=""
-		lvmLVS=$(lvs --noheadings | grep $VG | awk '/^ / {print $1}')
+		for VG in $lvmVGS; do
+			partitions=""
+			lvmLVS=$(lvs --noheadings | grep $VG | awk '/^ / {print $1}')
 		
-		for logical_volume in $lvmLVS; do
-			esVG=$(echo $lvmVG | sed 's/-/--/g')
-			esLV=$(echo $logical_volume | sed 's/-/--/g')
-			lvHD="/dev/mapper/$esVG-$esLV"
+			for logical_volume in $lvmLVS; do
+				esVG=$(echo $lvmVG | sed 's/-/--/g')
+				esLV=$(echo $logical_volume | sed 's/-/--/g')
+				lvHD="/dev/mapper/$esVG-$esLV"
 			
-			partitions="$partitions $lvHD "
-			lvOut="$esVG-$esLV"
-			fsType=`blkid -po udev "$lvHD" | grep FS_TYPE | awk -F'=' '{print $2}'`
-			shrinkFS $lvHD
-		done
+				partitions="$partitions $lvHD "
+				lvOut="$esVG-$esLV"
+				fsType=`blkid -po udev "$lvHD" | grep FS_TYPE | awk -F'=' '{print $2}'`
+				shrinkFS $lvHD
+			done
 		
-		uploadImage "true"
+			uploadImage "true"
 	
-		clear
+			ClearAndMoveDown
 		
-		for logical_volume in $lvmLVS; do	
-			esVG=$(echo $lvmVG | sed 's/-/--/g')
-			esLV=$(echo $logical_volume | sed 's/-/--/g')
-			lvHD="/dev/mapper/$esVG-$esLV"
-			fsType=`blkid -po udev "$lvHD" | grep FS_TYPE | awk -F'=' '{print $2}'`
-			expandFS $lvHD
+			
 		done
-	done
 	fi
-	
-	if [ -n "$hostScripts" ]; then
-	runScripts
-	fi
-
 done
 
+	log " shrunkVolumes: $shrunkVolumes"
+	for part in $shrunkVolumes; do
+		fsType=`blkid -po udev $part | grep FS_TYPE | awk -F'=' '{print $2}'`
+		expandFS $part
+	done
+
+	if [ -n "$hostScripts" ]; then
+		runScripts
+	fi
+	
 checkout
 
 	
